# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â•­â•´](bold green_dark)$all
$battery
[â•°â•´](bold green_dark)$character
"""
right_format = """$time $cmd_duration"""
add_newline = true
command_timeout = 10_000
palette = 'lover_light'

aws.disabled = true
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = false
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = false
nodejs.disabled = false
java.disabled = true
golang.disabled = true
conda.disabled = true
container.disabled = true
gcloud.disabled = true
localip.disabled = true
php.disabled = true
vagrant.disabled = true
git_metrics.disabled = true

[palettes.lover_light]
background = "#faf4ed"  # Lover's light background color
foreground = "#575279"
selection = "#dfdad9"
comment = "#907aa9"
red = "#D4618F"   # Lover's light 'Charm' color
green = "#286983"
yellow = "#F5E2B1"  # Lover's light 'Wheat' color
blue = "#56949f"
purple = "#CDAAD4"  # Lover's light 'Light Wisteria' color
cyan = "#6EB0E5"    # Lover's light 'Seagull' color
background_dark = "#1e1a27"
foreground_dark = "#dcd6f4"
selection_dark = "#2d283d"
comment_dark = "#7c7895"
red_dark = "#d75098"
green_dark = "#90cf8b"
yellow_dark = "#d1c467"
blue_dark = "#8a92c2"
purple_dark = "#d48fdc"
cyan_dark = "#8fcac9"
background_light = "#33303f"
foreground_light = "#f3f0ff"
selection_light = "#4a445b"
comment_light = "#a9a4c3"
red_light = "#ff7ebd"
green_light = "#ccf7bf"
yellow_light = "#f3ec9a"
blue_light = "#c9cde6"
purple_light = "#f1d9f6"
cyan_light = "#c9f1f0"
darkest_pink = "#B00544"

[line_break]
disabled = true

[character]
format = "$symbol "
success_symbol = "[ó°”°](green_dark bold)"
error_symbol = "[î™”](red)"
vimcmd_symbol = "[ î˜« ](yellow)"

[username]
format = "[ï€‡ $user]($style) "
style_root = "bold blue"
style_user = "bold cyan"
disabled = true

[hostname]
ssh_only = true
format = "[î‚¶](fg:blue bg:none)[$ssh_symbol](fg:blue_dark bg:blue)[î‚´](fg:blue bg:blue)[ $hostname]($style)[î‚´](fg:blue bg:none) "
style = "fg:bold blue_dark bg:blue"
ssh_symbol = "î¬"
trim_at = "-"
disabled = false

[ruby]
symbol = "î‘ "
format = "[î‚¶](fg:purple bg:none)[$symbol](fg:foreground bg:purple)[î‚´](bg:purple_light fg:purple)[ $version]($style)[î‚´](fg:purple_light bg:none) "
style = "fg:foreground bg:purple_light"

[git_branch]
symbol = "ï˜"
# symbol = "ğŸŒ± "
truncation_length = 7
truncation_symbol = ""
format = "[î‚¶](fg:yellow bg:none)[$symbol](fg:yellow_dark bg:yellow)[î‚´](fg:yellow bg:yellow)[$branch]($style)[î‚´](fg:yellow bg:none) "
style = "bold fg:yellow_dark bg:yellow"

[git_commit]
commit_hash_length = 7
disabled = false
tag_symbol = "ï€« "
tag_disabled = false
format = "[ï™ $hash$tag]($style) "

[git_status]
ignore_submodules = true
format="[î‚¶](fg:cyan_light bg:none)[$all_status$ahead_behind](fg:cyan bg:cyan_light)[î‚´](fg:cyan_light bg:none)"
conflicted = "âš”ï¸"
ahead = "ğŸï¸ğŸ’¨Ã—${count}"
behind = "ğŸ¢Ã—${count}"
diverged = "ğŸ”±ğŸï¸ğŸ’¨Ã—${ahead_count}ğŸ¢Ã—${behind_count}"
untracked = "ğŸ›¤ï¸ Ã—${count}"
stashed = "ğŸ“¦"
modified = "ğŸ“Ã—${count}"
staged = "ğŸ—ƒï¸ Ã—${count}"
renamed = "ğŸ“›Ã—${count}"
deleted = "ğŸ—‘ï¸ Ã—${count}"

[git_state]
merge = "ï™ MERGING"
rebase = "ï™ REBASING"
cherry_pick =  "ï™ PICKING"
style = "bold red"
revert = "ï™ REVERTING"
bisect = "ï™ BISECTING"

[directory]
read_only = " ï ½"
format = "[î‚¶](fg:purple_light bg:none)[î—¿](fg:purple_dark bg:purple_light)[î‚´](fg:purple_light bg:purple_light)[$path]($style)[î‚´](fg:purple_light bg:none) "
style = "bold italic fg:purple_dark bg:purple_light"
truncation_length = 3
truncate_to_repo=false

[directory.substitutions]
"~" = "ï€• ~"
"ï€• ~/Documents" = "î—¾ïœ˜~/Documents"
"ï€• ~/Downloads" = "ï€™ ~/Downloads"
"ï€• ~/Desktop"   = "ó°‡…ï ¡~/Desktop"
"ï€• ~/Music"     = "ï€ ~/Music"
"ï€• ~/Pictures"  = "ï€¾ ~/Pictures"
"ï€• ~/Library"   = "î®œ ~/Library"
"ï€• ~/Dropbox"   = "ï…« ~/Dropbox"
"ï€• ~/code"      = "ğŸ‘©â€ğŸ’»ï™¨~/code"
"ï€• ~/dev"       = "ğŸ‘©â€ğŸ’»ï™¨~/dev"
"ï€• ~/workspace" = "ğŸ’» ~/workspace"
"ï€• ~/.dotfiles" = "î­‘ dots"

[docker_context]
symbol = "ïŒˆ "

[time]
disabled = false
format="[î‚¶](fg:red_light bg:none)[ğŸ’–](fg:red_light bg:red_light)[î‚´](fg:red_light bg:red_light)[ $time]($style)[î‚´](fg:red_light bg:none)"
time_format = "%l:%m%p" #change to %R to only have HH:MM
style="fg:darkest_pink bg:red_light"

[cmd_duration]
min_time = 1
format = "[î‚¶]($style)[[ó°”Ÿ ](bg:green_light fg:green_dark)$duration](bg:green_light fg:green_dark)[î‚´ ]($style)"
disabled = false
style = "bg:none fg:green_light"

[battery]
full_symbol = "ó°‚„ "
charging_symbol = "î¬­ "
discharging_symbol = "ó°‚… "

[[battery.display]]
threshold = 25
style = "red"

[[battery.display]]
threshold = 50
style = "yellow"

[[battery.display]]
threshold = 101
style = "cyan_dark"

[os.symbols]
Alpine = "ïŒ€"
Arch = "ïŒƒ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Gentoo = "ïŒ"
Linux = "ïŒš"
Macos = "ïŒ‚"
Mint = "ïŒ"
NixOS = "ïŒ“"
OpenBSD = "ïœ¹"
openSUSE = "ïŒ”"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Ubuntu = "ïŒ›"
Unknown = "ïˆ­"
Windows = "ï…º"
